name: Update JSON (Bear)

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: sims/bear

jobs:
  update_json:
    name: Update JSON 1T
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: one target
        run: python generate_combo.py -t 1 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Bear 1T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_2:
    needs: [update_json]
    name: Update JSON 2T
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: two target
        run: python generate_combo.py -t 2 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Bear 2T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_3:
    needs: [update_json_2]
    name: Update JSON 3T
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: three target
        run: python generate_combo.py -t 3 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Bear 3T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_4:
    needs: [update_json_3]
    name: Update JSON 4T
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: four target
        run: python generate_combo.py -t 4 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Bear 4T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_5:
    needs: [update_json_4]
    name: Update JSON 5T
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: five target
        run: python generate_combo.py -t 5 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Bear 5T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_c:
    needs: [update_json_5]
    name: Update JSON Catweave
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: dungeon
        run: python generate_combo.py -c -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Bear Catweave"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_d:
    needs: [update_json_c]
    name: Update JSON Dungeon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: dungeon
        run: python generate_combo.py -d -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Bear Dungeon"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_hoa:
    needs: [update_json_d]
    name: Update JSON HoA Route
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: dungeon
        run: python generate_combo.py --hoa -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Bear HoA Route"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json
